### ISSUE TITLE
Wreid behaviour with "Texture Pages" button

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#11]
If i select it and import a object like lara (Lara Full Model) then it throw a error when creating material.

**Comment by veeti512** [comment]
Can you send me please a wad that throws that error? I'm not able to replicate

**Comment by veeti512** [comment]
Also the error message would be helpful

**Comment by TokyoSU** [comment]
there for the error message (when selecting Lara Full Model and Texture Pages button):
```
Python: Traceback (most recent call last):
  File "C:\Users\vleva\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\wadblender-master\import_wad.py", line 298, in execute
    material = createPageMaterial(texture_path, context)
  File "C:\Users\vleva\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\wadblender-master\create_materials.py", line 124, in createPageMaterial
    set_idx = len(obj.material_slots)
AttributeError: 'NoneType' object has no attribute 'material_slots'

location: <unknown location>:-1
```
Ive used the lara tr1 to test it, it seem all wad cause that.

**Comment by veeti512** [comment]
It should be fixed now!
